AZURE_LOCATION: 'westeurope'
RESOURCE_NAME_PREFIX: 'apimdemo'
ENVIRONMENT_TAG: 'prod'
DEPLOYMENT_NAME: 'ase-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'github.com/jamelachahbar'
CICD_AGENT_TYPE: 'github'
CERT_TYPE: 'selfsigned'
